MIN_MAP = {
    0: '',
    5: 'five-min',
    10: 'ten-min',
    15: 'quarter',
    20: 'twenty-min-f',
    25: 'twenty-min-f',
    30: 'half',
}
HOUR_MAP = {
    1: 'one',
    2: 'two',
    3: 'three',
    4: 'four',
    5: 'five',
    6: 'six',
    7: 'seven',
    8: 'eight',
    9: 'nine',
    10: 'ten',
    11: 'eleven',
    12: 'twelve',
}
GRID = {
    'grid': [[{'I': 'it'},
              {'T': 'it'},
              {'L': 'x'},
              {'I': 'is'},
              {'S': 'is'},
              {'A': 'x'},
              {'S': 'x'},
              {'A': 'am'},
              {'M': 'am'},
              {'P': 'pm'},
              {'M': 'pm'}, ],
             [{'A': 'a'},
              {'C': 'x'},
              {'Q': 'quarter'},
              {'U': 'quarter'},
              {'A': 'quarter'},
              {'R': 'quarter'},
              {'T': 'quarter'},
              {'E': 'quarter'},
              {'R': 'quarter'},
              {'D': 'x'},
              {'C': 'x'}, ],
             [{'T': 'twenty-min-f'},
              {'W': 'twenty-min-f'},
              {'E': 'twenty-min-f'},
              {'N': 'twenty-min-f'},
              {'T': 'twenty-min-f'},
              {'Y': 'twenty-min-f'},
              {'F': 'five-min'},
              {'I': 'five-min'},
              {'V': 'five-min'},
              {'E': 'five-min'},
              {'X': 'x'}, ],
             [{'H': 'half'},
              {'A': 'half'},
              {'L': 'half'},
              {'F': 'half'},
              {'S': 'x'},
              {'T': 'ten-min'},
              {'E': 'ten-min'},
              {'N': 'ten-min'},
              {'F': 'x'},
              {'T': 'to'},
              {'O': 'to'}, ],
             [{'P': 'past'},
              {'A': 'past'},
              {'S': 'past'},
              {'T': 'past'},
              {'E': 'x'},
              {'R': 'x'},
              {'U': 'x'},
              {'N': 'nine'},
              {'I': 'nine'},
              {'N': 'nine'},
              {'E': 'nine'}, ],
             [{'O': 'one'},
              {'N': 'one'},
              {'E': 'one'},
              {'S': 'six'},
              {'I': 'six'},
              {'X': 'six'},
              {'T': 'three'},
              {'H': 'three'},
              {'R': 'three'},
              {'E': 'three'},
              {'E': 'three'}, ],
             [{'F': 'four'},
              {'O': 'four'},
              {'U': 'four'},
              {'R': 'four'},
              {'F': 'five'},
              {'I': 'five'},
              {'V': 'five'},
              {'E': 'five'},
              {'T': 'two'},
              {'W': 'two'},
              {'O': 'two'}, ],
             [{'E': 'eight'},
              {'I': 'eight'},
              {'G': 'eight'},
              {'H': 'eight'},
              {'T': 'eight'},
              {'E': 'eleven'},
              {'L': 'eleven'},
              {'E': 'eleven'},
              {'V': 'eleven'},
              {'E': 'eleven'},
              {'N': 'eleven'}, ],
             [{'S': 'seven'},
              {'E': 'seven'},
              {'V': 'seven'},
              {'E': 'seven'},
              {'N': 'seven'},
              {'T': 'twelve'},
              {'W': 'twelve'},
              {'E': 'twelve'},
              {'L': 'twelve'},
              {'V': 'twelve'},
              {'E': 'twelve'}, ],
             [{'T': 'ten'},
              {'E': 'ten'},
              {'N': 'ten'},
              {'S': 'x'},
              {'O\'': 'o'},
              {'E': 'x'},
              {'C': 'clock'},
              {'L': 'clock'},
              {'O': 'clock'},
              {'C': 'clock'},
              {'K': 'clock'}, ],

             ]}
